# Generated by Django 5.1.3 on 2025-07-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField(help_text='Extracted text from the uploaded resume (PDF or text)')),
                ('jd_text', models.TextField(help_text='Job description text pasted by the user')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(blank=True, help_text='TF-IDF + Cosine Similarity score', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_resume', models.TextField(help_text='ATS-friendly, customized resume')),
                ('interview_questions', models.TextField(help_text='Generated interview Q&A (JSON or plain text)')),
                ('explanation', models.TextField(help_text='Plain English explanation of the match')),
                ('user_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.userinput')),
            ],
        ),
    ]
