# Generated by Django 5.1.3 on 2025-08-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userinput_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='message',
            new_name='bot_response',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='response',
            new_name='user_message',
        ),
    ]
